SCC Python SDK
IBM/scc-python-sdk pull request #37
Opened 2023-08-22 02:28 UTC by pbvaishnavi

## PR summary

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2023-08-22 21:35 UTC, tyao117 requested changes
please change `componenet_name` to `component_name`

2023-08-22 21:35 UTC, tyao117 commented on ibm_scc/security_and_compliance_center_api_v3.py
> +        componenet_name: str = None,
```suggestion
        component_name: str = None,
```

2023-08-22 21:35 UTC, tyao117 commented on ibm_scc/security_and_compliance_center_api_v3.py
> +    :attr str componenet_name: (optional) The component name.
```suggestion
    :attr str component_name: (optional) The component name.
```

2023-08-22 21:35 UTC, tyao117 commented on ibm_scc/security_and_compliance_center_api_v3.py
> +        :param str componenet_name: (optional) The component name.
```suggestion
        :param str component_name: (optional) The component name.
```

2023-08-22 21:35 UTC, tyao117 commented on ibm_scc/security_and_compliance_center_api_v3.py
> +        self.componenet_name = componenet_name
```suggestion
        self.component_name = component_name
```

2023-08-23 15:29 UTC, pbvaishnavi commented on ibm_scc/security_and_compliance_center_api_v3.py
> +        componenet_name: str = None,
updated

2023-08-23 15:29 UTC, pbvaishnavi commented on ibm_scc/security_and_compliance_center_api_v3.py
> +        self.componenet_name = componenet_name
Resolved.

2023-09-15 09:09 UTC, archanaponnada commented
Closing this as the changes under these PR are covered under PR#45

2023-09-15 09:09 UTC, closed without merging